apiVersion: integration/v1
kind: Integration
name: ansible
channel: stable
version: v20220428
summary: Ansible
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-ansible
source: https://github.com/relay-integrations/relay-ansible

description: |
  Ansible is an open-source configuration management and application deployment tool.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
- configuration
